title: Wonderland
author: XeCtvi
email: xeec@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Here's the content for Google Search. Come to search me~

# social links
twitter_username: your-twitter-handle
github_username:  XeCtvi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

